/**
 * Wish List API
 * A REST API to control wish lists
 *
 * OpenAPI spec version: 1.0.0
 * Contact: caleb_bertsch@sweetwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WishListApi) {
      root.WishListApi = {};
    }
    root.WishListApi.ItemTransferRequest = factory(root.WishListApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ItemTransferRequest model module.
   * @module model/ItemTransferRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ItemTransferRequest</code>.
   * @alias module:model/ItemTransferRequest
   * @class
   * @param targetListId {Number} 
   * @param transferType {module:model/ItemTransferRequest.TransferTypeEnum} 
   */
  var exports = function(targetListId, transferType) {
    var _this = this;

    _this['target_list_id'] = targetListId;
    _this['transfer_type'] = transferType;

  };

  /**
   * Constructs a <code>ItemTransferRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ItemTransferRequest} obj Optional instance to populate.
   * @return {module:model/ItemTransferRequest} The populated <code>ItemTransferRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('target_list_id')) {
        obj['target_list_id'] = ApiClient.convertToType(data['target_list_id'], 'Number');
      }
      if (data.hasOwnProperty('transfer_type')) {
        obj['transfer_type'] = ApiClient.convertToType(data['transfer_type'], 'String');
      }
      if (data.hasOwnProperty('item_ids')) {
        obj['item_ids'] = ApiClient.convertToType(data['item_ids'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} target_list_id
   */
  exports.prototype['target_list_id'] = undefined;
  /**
   * @member {module:model/ItemTransferRequest.TransferTypeEnum} transfer_type
   */
  exports.prototype['transfer_type'] = undefined;
  /**
   * @member {Array.<Number>} item_ids
   */
  exports.prototype['item_ids'] = undefined;


  /**
   * Allowed values for the <code>transfer_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TransferTypeEnum = {
    /**
     * value: "all"
     * @const
     */
    "all": "all",
    /**
     * value: "specific"
     * @const
     */
    "specific": "specific"  };


  return exports;
}));


