/**
 * Wish List API
 * A REST API to control wish lists
 *
 * OpenAPI spec version: 1.0.0
 * Contact: caleb_bertsch@sweetwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WishListApi) {
      root.WishListApi = {};
    }
    root.WishListApi.Items = factory(root.WishListApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Items model module.
   * @module model/Items
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Items</code>.
   * @alias module:model/Items
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Items</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Items} obj Optional instance to populate.
   * @return {module:model/Items} The populated <code>Items</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('item_ids')) {
        obj['item_ids'] = ApiClient.convertToType(data['item_ids'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} item_ids
   */
  exports.prototype['item_ids'] = undefined;



  return exports;
}));


