/**
 * Wish List API
 * A REST API to control wish lists
 *
 * OpenAPI spec version: 1.0.0
 * Contact: caleb_bertsch@sweetwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WishListApi) {
      root.WishListApi = {};
    }
    root.WishListApi.WishListItemParameter = factory(root.WishListApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WishListItemParameter model module.
   * @module model/WishListItemParameter
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WishListItemParameter</code>.
   * @alias module:model/WishListItemParameter
   * @class
   * @param type {module:model/WishListItemParameter.TypeEnum} 
   */
  var exports = function(type) {
    var _this = this;

    _this['type'] = type;



  };

  /**
   * Constructs a <code>WishListItemParameter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WishListItemParameter} obj Optional instance to populate.
   * @return {module:model/WishListItemParameter} The populated <code>WishListItemParameter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('note')) {
        obj['note'] = ApiClient.convertToType(data['note'], 'String');
      }
      if (data.hasOwnProperty('idea')) {
        obj['idea'] = ApiClient.convertToType(data['idea'], 'String');
      }
      if (data.hasOwnProperty('itemid')) {
        obj['itemid'] = ApiClient.convertToType(data['itemid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/WishListItemParameter.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} note
   */
  exports.prototype['note'] = undefined;
  /**
   * @member {String} idea
   */
  exports.prototype['idea'] = undefined;
  /**
   * @member {String} itemid
   */
  exports.prototype['itemid'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "product"
     * @const
     */
    "product": "product",
    /**
     * value: "idea"
     * @const
     */
    "idea": "idea"  };


  return exports;
}));


