/**
 * Wish List API
 * A REST API to control wish lists
 *
 * OpenAPI spec version: 1.0.0
 * Contact: caleb_bertsch@sweetwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WishListApi) {
      root.WishListApi = {};
    }
    root.WishListApi.WishListProduct = factory(root.WishListApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WishListProduct model module.
   * @module model/WishListProduct
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WishListProduct</code>.
   * A wish list item representing a product
   * @alias module:model/WishListProduct
   * @class
   * @param id {Number} 
   * @param sortIndex {Number} 
   * @param type {String} 
   * @param itemid {String} 
   */
  var exports = function(id, sortIndex, type, itemid) {
    var _this = this;

    _this['id'] = id;
    _this['sort_index'] = sortIndex;

    _this['type'] = type;
    _this['itemid'] = itemid;
  };

  /**
   * Constructs a <code>WishListProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WishListProduct} obj Optional instance to populate.
   * @return {module:model/WishListProduct} The populated <code>WishListProduct</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('sort_index')) {
        obj['sort_index'] = ApiClient.convertToType(data['sort_index'], 'Number');
      }
      if (data.hasOwnProperty('note')) {
        obj['note'] = ApiClient.convertToType(data['note'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('itemid')) {
        obj['itemid'] = ApiClient.convertToType(data['itemid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} sort_index
   */
  exports.prototype['sort_index'] = undefined;
  /**
   * @member {String} note
   */
  exports.prototype['note'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} itemid
   */
  exports.prototype['itemid'] = undefined;



  return exports;
}));


