/**
 * Wish List API
 * A REST API to control wish lists
 *
 * OpenAPI spec version: 1.0.0
 * Contact: caleb_bertsch@sweetwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ERRORUNKNOWN', 'model/WishListItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ERRORUNKNOWN'), require('./WishListItem'));
  } else {
    // Browser globals (root is window)
    if (!root.WishListApi) {
      root.WishListApi = {};
    }
    root.WishListApi.WishListProduct = factory(root.WishListApi.ApiClient, root.WishListApi.ERRORUNKNOWN, root.WishListApi.WishListItem);
  }
}(this, function(ApiClient, ERRORUNKNOWN, WishListItem) {
  'use strict';




  /**
   * The WishListProduct model module.
   * @module model/WishListProduct
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WishListProduct</code>.
   * A wish list item representing a product
   * @alias module:model/WishListProduct
   * @class
   * @extends module:model/WishListItem
   * @param id {Number} 
   * @param type {module:model/ERRORUNKNOWN} 
   * @param sortIndex {Number} 
   * @param itemid {String} 
   */
  var exports = function(id, type, sortIndex, itemid) {
    var _this = this;
    WishListItem.call(_this, id, type, sortIndex);

    _this['itemid'] = itemid;
  };

  /**
   * Constructs a <code>WishListProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WishListProduct} obj Optional instance to populate.
   * @return {module:model/WishListProduct} The populated <code>WishListProduct</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      WishListItem.constructFromObject(data, obj);
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], ERRORUNKNOWN);
      }
      if (data.hasOwnProperty('itemid')) {
        obj['itemid'] = ApiClient.convertToType(data['itemid'], 'String');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(WishListItem.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/ERRORUNKNOWN} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} itemid
   */
  exports.prototype['itemid'] = undefined;



  return exports;
}));


