/**
 * Wish List API
 * A REST API to control wish lists
 *
 * OpenAPI spec version: 1.0.0
 * Contact: caleb_bertsch@sweetwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WishListParameter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WishListParameter'));
  } else {
    // Browser globals (root is window)
    if (!root.WishListApi) {
      root.WishListApi = {};
    }
    root.WishListApi.WishList = factory(root.WishListApi.ApiClient, root.WishListApi.WishListParameter);
  }
}(this, function(ApiClient, WishListParameter) {
  'use strict';




  /**
   * The WishList model module.
   * @module model/WishList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WishList</code>.
   * @alias module:model/WishList
   * @class
   * @extends module:model/WishListParameter
   * @param name {String} 
   * @param id {Number} 
   * @param token {String} 
   */
  var exports = function(name, id, token) {
    var _this = this;
    WishListParameter.call(_this, name);
    _this['id'] = id;
    _this['token'] = token;

  };

  /**
   * Constructs a <code>WishList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WishList} obj Optional instance to populate.
   * @return {module:model/WishList} The populated <code>WishList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      WishListParameter.constructFromObject(data, obj);
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('token')) {
        obj['token'] = ApiClient.convertToType(data['token'], 'String');
      }
      if (data.hasOwnProperty('items_count')) {
        obj['items_count'] = ApiClient.convertToType(data['items_count'], 'Number');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(WishListParameter.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} token
   */
  exports.prototype['token'] = undefined;
  /**
   * @member {Number} items_count
   */
  exports.prototype['items_count'] = undefined;



  return exports;
}));


