/**
 * Wish List API
 * A REST API to control wish lists
 *
 * OpenAPI spec version: 1.0.0
 * Contact: caleb_bertsch@sweetwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse200', 'model/InlineResponse2001', 'model/InlineResponse2002', 'model/InlineResponse2003', 'model/InlineResponse2004', 'model/ItemTransferRequest', 'model/Items', 'model/WishList', 'model/WishListIdea', 'model/WishListItem', 'model/WishListItemParameter', 'model/WishListParameter', 'model/WishListProduct', 'api/ListItemsApi', 'api/ListsApi', 'api/SearchApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/InlineResponse200'), require('./model/InlineResponse2001'), require('./model/InlineResponse2002'), require('./model/InlineResponse2003'), require('./model/InlineResponse2004'), require('./model/ItemTransferRequest'), require('./model/Items'), require('./model/WishList'), require('./model/WishListIdea'), require('./model/WishListItem'), require('./model/WishListItemParameter'), require('./model/WishListParameter'), require('./model/WishListProduct'), require('./api/ListItemsApi'), require('./api/ListsApi'), require('./api/SearchApi'));
  }
}(function(ApiClient, InlineResponse200, InlineResponse2001, InlineResponse2002, InlineResponse2003, InlineResponse2004, ItemTransferRequest, Items, WishList, WishListIdea, WishListItem, WishListItemParameter, WishListParameter, WishListProduct, ListItemsApi, ListsApi, SearchApi) {
  'use strict';

  /**
   * A_REST_API_to_control_wish_lists.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var WishListApi = require('index'); // See note below*.
   * var xxxSvc = new WishListApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new WishListApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new WishListApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new WishListApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200: InlineResponse200,
    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001: InlineResponse2001,
    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002: InlineResponse2002,
    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003: InlineResponse2003,
    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004: InlineResponse2004,
    /**
     * The ItemTransferRequest model constructor.
     * @property {module:model/ItemTransferRequest}
     */
    ItemTransferRequest: ItemTransferRequest,
    /**
     * The Items model constructor.
     * @property {module:model/Items}
     */
    Items: Items,
    /**
     * The WishList model constructor.
     * @property {module:model/WishList}
     */
    WishList: WishList,
    /**
     * The WishListIdea model constructor.
     * @property {module:model/WishListIdea}
     */
    WishListIdea: WishListIdea,
    /**
     * The WishListItem model constructor.
     * @property {module:model/WishListItem}
     */
    WishListItem: WishListItem,
    /**
     * The WishListItemParameter model constructor.
     * @property {module:model/WishListItemParameter}
     */
    WishListItemParameter: WishListItemParameter,
    /**
     * The WishListParameter model constructor.
     * @property {module:model/WishListParameter}
     */
    WishListParameter: WishListParameter,
    /**
     * The WishListProduct model constructor.
     * @property {module:model/WishListProduct}
     */
    WishListProduct: WishListProduct,
    /**
     * The ListItemsApi service constructor.
     * @property {module:api/ListItemsApi}
     */
    ListItemsApi: ListItemsApi,
    /**
     * The ListsApi service constructor.
     * @property {module:api/ListsApi}
     */
    ListsApi: ListsApi,
    /**
     * The SearchApi service constructor.
     * @property {module:api/SearchApi}
     */
    SearchApi: SearchApi
  };

  return exports;
}));
