/**
 * Wish List API
 * A REST API to control wish lists
 *
 * OpenAPI spec version: 1.0.0
 * Contact: caleb_bertsch@sweetwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WishListApi);
  }
}(this, function(expect, WishListApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WishListApi.ListsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListsApi', function() {
    describe('listsGet', function() {
      it('should call listsGet successfully', function(done) {
        //uncomment below and update the code to test listsGet
        //instance.listsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listsListIdDelete', function() {
      it('should call listsListIdDelete successfully', function(done) {
        //uncomment below and update the code to test listsListIdDelete
        //instance.listsListIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listsListIdGet', function() {
      it('should call listsListIdGet successfully', function(done) {
        //uncomment below and update the code to test listsListIdGet
        //instance.listsListIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listsListIdItemsListItemIdRestorePost', function() {
      it('should call listsListIdItemsListItemIdRestorePost successfully', function(done) {
        //uncomment below and update the code to test listsListIdItemsListItemIdRestorePost
        //instance.listsListIdItemsListItemIdRestorePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listsListIdPatch', function() {
      it('should call listsListIdPatch successfully', function(done) {
        //uncomment below and update the code to test listsListIdPatch
        //instance.listsListIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listsListIdRestorePost', function() {
      it('should call listsListIdRestorePost successfully', function(done) {
        //uncomment below and update the code to test listsListIdRestorePost
        //instance.listsListIdRestorePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listsPost', function() {
      it('should call listsPost successfully', function(done) {
        //uncomment below and update the code to test listsPost
        //instance.listsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
